-- Moni — the recurring view (#15).
--
-- Generated by drizzle-kit, then hand-corrected in two places; both are
-- noted inline below. No companion RLS migration is needed: every table
-- touched here already has policies (0001), and a new column inherits them.
--
-- See docs/adr/0005-a-merchant-is-a-match-text-that-got-promoted.md and
--     docs/adr/0006-the-recurring-view-stores-nothing-and-recurring-series-is-deleted.md

-- ---------------------------------------------------------------------------
-- 1. Drop the detection state that was never written (ADR 0006).
--
--    CASCADE takes recurring_series' policies, its trigger, AND the FK that
--    entries holds on it — which is why the generated
--    `ALTER TABLE entries DROP CONSTRAINT entries_owner_id_recurring_...`
--    was removed from this file rather than kept: by the time it ran, the
--    constraint no longer existed and the statement errored.
-- ---------------------------------------------------------------------------
DROP TABLE "recurring_series" CASCADE;--> statement-breakpoint
ALTER TABLE "entries" DROP COLUMN "recurring_series_id";--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 2. The recurring view's only gate.
-- ---------------------------------------------------------------------------
ALTER TABLE "categories" ADD COLUMN "is_recurring" boolean DEFAULT false NOT NULL;--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 3. Merchant identity (ADR 0005).
--
--    drizzle-kit emitted `ADD COLUMN "match_text_ct" bytea NOT NULL` in one
--    statement, which fails on any database that already holds merchant rows.
--    Some do: the app has never written this table, but scripts/seed-demo.ts
--    has, so every dev database seeded before this migration has two.
--
--    Those rows cannot be given a match text here. `name_ct` is encrypted
--    under a per-user data key that lives in RAM only and that a migration
--    has no access to by design (security-design-principles.md), so there is
--    nothing to derive one from. They are dropped instead — re-seeding
--    recreates them, and for real data the next sync resolves merchants
--    properly. Entries pointing at them are unlinked first, or the FK
--    would block the delete.
-- ---------------------------------------------------------------------------
ALTER TABLE "merchants" ADD COLUMN "match_text_ct" "bytea";--> statement-breakpoint
ALTER TABLE "merchants" ADD COLUMN "cadence_override" text;--> statement-breakpoint

UPDATE "entries" SET "merchant_id" = NULL
  WHERE "merchant_id" IN (SELECT "id" FROM "merchants" WHERE "match_text_ct" IS NULL);--> statement-breakpoint
DELETE FROM "merchants" WHERE "match_text_ct" IS NULL;--> statement-breakpoint

ALTER TABLE "merchants" ALTER COLUMN "match_text_ct" SET NOT NULL;
