// The lucide icons a category may use, as a closed allowlist.
//
// Two reasons it is a fixed list rather than "any lucide name":
//   - `categories.icon` is a free-text column, so without an allowlist a
//     typo (or a name that vanishes in a lucide major) renders nothing and
//     the row silently loses its icon.
//   - the icon picker needs something finite to show. Maybe caps theirs at
//     44 for exactly this reason; the list below is the union of every icon
//     the shipped set uses plus a small general-purpose tail.
//
// Imports are explicit and named on purpose: a name that does not exist in
// lucide-react fails `npm run typecheck` here, rather than at render time in
// a browser nobody is watching.
import {
  ArrowLeftRight,
  Baby,
  Banknote,
  Bath,
  Bike,
  BookOpen,
  Briefcase,
  Building,
  Bus,
  Cake,
  CalendarDays,
  Car,
  Cat,
  CircleDollarSign,
  CircleParking,
  Coffee,
  Coins,
  CreditCard,
  Dog,
  Drama,
  Droplet,
  Dumbbell,
  Folder,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  HandHeart,
  Handshake,
  Heart,
  HeartHandshake,
  House,
  Key,
  Landmark,
  Laptop,
  Music,
  Package,
  Percent,
  PiggyBank,
  Pill,
  Plane,
  Plug,
  Receipt,
  Scale,
  Scissors,
  ShieldCheck,
  ShieldPlus,
  Shirt,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Smile,
  Sofa,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Ticket,
  TrainFront,
  TrendingUp,
  Tv,
  Umbrella,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Kebab-case name (what `categories.icon` stores) -> component. */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "arrow-left-right": ArrowLeftRight,
  baby: Baby,
  banknote: Banknote,
  bath: Bath,
  bike: Bike,
  "book-open": BookOpen,
  briefcase: Briefcase,
  building: Building,
  bus: Bus,
  cake: Cake,
  "calendar-days": CalendarDays,
  car: Car,
  cat: Cat,
  "circle-dollar-sign": CircleDollarSign,
  "circle-parking": CircleParking,
  coffee: Coffee,
  coins: Coins,
  "credit-card": CreditCard,
  dog: Dog,
  drama: Drama,
  droplet: Droplet,
  dumbbell: Dumbbell,
  folder: Folder,
  fuel: Fuel,
  "gamepad-2": Gamepad2,
  gift: Gift,
  "graduation-cap": GraduationCap,
  hammer: Hammer,
  "hand-heart": HandHeart,
  handshake: Handshake,
  heart: Heart,
  "heart-handshake": HeartHandshake,
  house: House,
  key: Key,
  landmark: Landmark,
  laptop: Laptop,
  music: Music,
  package: Package,
  percent: Percent,
  "piggy-bank": PiggyBank,
  pill: Pill,
  plane: Plane,
  plug: Plug,
  receipt: Receipt,
  scale: Scale,
  scissors: Scissors,
  "shield-check": ShieldCheck,
  "shield-plus": ShieldPlus,
  shirt: Shirt,
  "shopping-basket": ShoppingBasket,
  "shopping-cart": ShoppingCart,
  smartphone: Smartphone,
  smile: Smile,
  sofa: Sofa,
  sprout: Sprout,
  star: Star,
  stethoscope: Stethoscope,
  sun: Sun,
  tag: Tag,
  ticket: Ticket,
  "train-front": TrainFront,
  "trending-up": TrendingUp,
  tv: Tv,
  umbrella: Umbrella,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  wifi: Wifi,
  wine: Wine,
  wrench: Wrench,
  zap: Zap,
};

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICONS);

export const DEFAULT_CATEGORY_ICON = "tag";

/** Resolves a stored icon name, degrading to a neutral tag rather than
 * throwing — an unknown name is a cosmetic problem, not a page crash. */
export function categoryIcon(name: string | null): LucideIcon {
  return (name && CATEGORY_ICONS[name]) || Tag;
}

export function isCategoryIcon(name: string): boolean {
  return Object.hasOwn(CATEGORY_ICONS, name);
}
